# ===================================================================
# 修正后的SHL数据集配置文件 - 基于真实传感器数据
# ===================================================================

# 实验基本信息
name: "SHL_MultiModal_Corrected"
description: "基于SHL数据集真实传感器的多模态融合实验"
version: "2.0"
author: "MazeruHAR Team"
created_date: "2024-12-01"

# 环境配置
environment:
  seed: 42
  device: "auto"
  num_workers: 4
  pin_memory: true

# 数据集配置
dataset:
  name: "SHL"
  path: "datasets/datasetStandardized/SHL_Multimodal/"
  preprocessing:
    window_size: 128
    step_size: 64
    sample_rate: 100
    normalize_per_sample: true
  activity_labels:
    0: "Still"      # 原标签1，重编码为0
    1: "Walking"    # 原标签2，重编码为1
    2: "Run"        # 原标签3，重编码为2
    3: "Bike"       # 原标签4，重编码为3
    4: "Car"        # 原标签5，重编码为4
    5: "Bus"        # 原标签6，重编码为5
    6: "Train"      # 原标签7，重编码为6
    7: "Subway"     # 原标签8，重编码为7
  data_split:
    train: 0.7
    validation: 0.15
    test: 0.15
    stratify: true
    
  # 基于SHL数据集真实传感器的模态配置
  modalities:
    imu:
      enabled: true
      channels: 6         # 加速度计(3) + 陀螺仪(3)
      sensors: ["acc", "gyro"]
      column_indices: [1, 2, 3, 4, 5, 6]
      
    magnetometer:
      enabled: true
      channels: 3         # 磁力计 X, Y, Z
      sensors: ["mag"]
      column_indices: [7, 8, 9]
      
    orientation:
      enabled: true
      channels: 4         # 四元数 W, X, Y, Z
      sensors: ["ori"]
      column_indices: [10, 11, 12, 13]
      
    gravity:
      enabled: true
      channels: 3         # 重力向量 X, Y, Z
      sensors: ["gra"]
      column_indices: [14, 15, 16]
      
    linear_acceleration:
      enabled: true
      channels: 3         # 线性加速度 X, Y, Z
      sensors: ["lacc"]
      column_indices: [17, 18, 19]

# 模型架构配置
architecture:
  type: "DynamicHarModel"
  num_classes: 8
  
  experts:
    imu_expert:
      type: "transformer"
      modality: "imu"
      params:
        input_shape: [128, 6]
        output_dim: 128
        d_model: 256
        nhead: 8
        num_layers: 4
        dim_feedforward: 512
        dropout: 0.1
        
    magnetometer_expert:
      type: "cnn"
      modality: "magnetometer"
      params:
        input_shape: [128, 3]
        output_dim: 64
        filters: [32, 64, 128]
        kernel_sizes: [3, 3, 3]
        dropout: 0.2
        
    orientation_expert:
      type: "rnn"
      modality: "orientation"
      params:
        input_shape: [128, 4]
        output_dim: 64
        hidden_dim: 128
        num_layers: 2
        rnn_type: "LSTM"
        bidirectional: true
        dropout: 0.2
        
    gravity_expert:
      type: "cnn"
      modality: "gravity"
      params:
        input_shape: [128, 3]
        output_dim: 32
        filters: [16, 32, 64]
        kernel_sizes: [3, 3, 3]
        dropout: 0.2
        
    linear_acceleration_expert:
      type: "cnn"
      modality: "linear_acceleration"
      params:
        input_shape: [128, 3]
        output_dim: 32
        filters: [16, 32, 64]
        kernel_sizes: [3, 3, 3]
        dropout: 0.2
  
  # 特征融合配置
  fusion:
    strategy: "concatenate"
    params: {}
      
  # 分类器配置
  classifier:
    type: "MLP"
    input_dim: 320     # 128 + 64 + 64 + 32 + 32 = 320
    layers: [320, 256, 128, 64, 8]
    activation: "relu"
    dropout: 0.3

# 训练配置
training:
  epochs: 100
  batch_size: 64
  learning_rate: 0.0005
  weight_decay: 0.01
  optimizer: "AdamW"
  
  scheduler: "step"
  scheduler_params:
    step_size: 50
    gamma: 0.5
  
  loss: "CrossEntropyLoss"
  label_smoothing: 0.1
  gradient_clip_norm: 1.0
  
  early_stopping:
    enabled: true
    patience: 25
    monitor: "val_f1"
    mode: "max"
    min_delta: 0.001

# 验证和测试配置
evaluation:
  metrics: ["accuracy", "f1_macro", "f1_weighted", "precision", "recall"]
  test_during_training: false
  validation_frequency: 1

# 可视化配置
visualization:
  enabled: true
  plots:
    learning_curves: true
    confusion_matrix: true
    class_distribution: true
    sensor_analysis: true
  figure_size: [12, 8]
  dpi: 300
  save_format: "png"

# 输出配置
output:
  base_dir: "./results"
  experiment_name: "shl_multimodal_corrected"
  save_checkpoints: true
  save_best_only: true
  verbose: true

# 调试配置
debug:
  enabled: true
  print_model_summary: true
  print_data_shapes: true
  print_batch_info: true
  log_level: "INFO"

# 数据加载器配置
dataloader:
  train:
    batch_size: 64
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: true
  
  validation:
    batch_size: 64
    shuffle: false
    num_workers: 4
    pin_memory: true
    drop_last: false
  
  test:
    batch_size: 64
    shuffle: false
    num_workers: 4
    pin_memory: true
    drop_last: false