# 实验元数据
name: SHL_MultiModal_YAML_Experiment
seed: 42
device: auto
output_dir: './results/shl_multimodal_run'
save_checkpoints: true

# 数据集配置
dataset:
  name: shl  # <-- 对应 datasets/shl.py, 用于动态加载
  path: /Users/zilongzeng/Research/MazeruHAR/datasets/datasetStandardized/SHL_Multimodal/
  activity_labels:
    - Still
    - Walking
    - Run
    - Bike
    - Car
    - Bus
    - Train
    - Subway
  split:
    train: 0.7
    val: 0.15
    test: 0.15

# 模型架构配置: 使用多专家模型
architecture:
  type: multi_expert # <-- 对应 models/multi_expert.py
  num_classes: 8 # 数据集中的类别总数

  # 定义每个模态/传感器的专家模型
  experts:
    # 专家1：处理IMU数据 (假设前9个通道是IMU)
    imu_expert:
      type: cbranchformer # <-- 对应 models/cbranchformer.py
      input_slice: [0, 9] # 使用特征的第0到第8列 (共9个通道)
      params:
        projection_dim: 128
        num_heads: 4
        num_layers: 2
        patch_size: 16
        time_step: 16
        conv_kernel_size: 15
        dropout_rate: 0.1

    # 专家2：处理磁力计数据 (假设后3个通道是磁力计)
    magnetometer_expert:
      type: lstm # <-- 对应 models/lstm.py
      input_slice: [9, 12] # 使用特征的第9到第11列 (共3个通道)
      params:
        hidden_dim: 64
        num_layers: 2
        dropout_rate: 0.2
        bidirectional: true

  # 定义特征融合策略
  fusion:
    type: concatenate # 融合方式 (当前支持 'concatenate')
    dropout_rate: 0.3

# 训练超参数配置
training:
  epochs: 100
  batch_size: 32
  optimizer:
    type: Adam
    params:
      lr: 0.001
      weight_decay: 0.0001
  scheduler:
    type: CosineAnnealingLR
    params:
      T_max: 100
  gradient_clip_norm: 1.0
  early_stopping_patience: 10