# config/default_configs/shl_config.yaml
# SHL数据集多模态实验配置

name: "SHL_MultiModal_Experiment"

# 数据集配置
dataset:
  name: "SHL"
  path: "./datasets/SHL"
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  
  # SHL数据集活动标签
  activity_labels:
    - "Standing"
    - "Walking"
    - "Running"
    - "Biking"
    - "Car"
    - "Bus"
    - "Train"
    - "Subway"
  
  # 模态配置
  modalities:
    - name: "imu"
      channels: 6  # 3轴加速度计 + 3轴陀螺仪
      sequence_length: 200
      expert_type: "cbranchformer"
      expert_params:
        projection_dim: 192
        num_heads: 4
        num_layers: 3
        patch_size: 16
        time_step: 16
        conv_kernel_size: 15
        dropout_rate: 0.1
        use_tokens: true
      preprocessing:
        normalize: true
        filter_freq: 20
        window_size: 200
        overlap: 0.5
        
    - name: "pressure"
      channels: 1  # 气压传感器
      sequence_length: 200
      expert_type: "lstm"
      expert_params:
        hidden_dim: 64
        num_layers: 2
        dropout_rate: 0.1
        bidirectional: true
      preprocessing:
        normalize: true
        window_size: 200
        overlap: 0.5

# 模型架构配置
architecture:
  # 专家模型配置
  experts:
    imu:
      type: "cbranchformer"
      params:
        projection_dim: 192
        num_heads: 4
        num_layers: 3
        patch_size: 16
        time_step: 16
        conv_kernel_size: 15
        conv_expansion_factor: 2
        ffn_expansion_factor: 4
        dropout_rate: 0.1
        use_tokens: true
        filter_attention_head: 1
        conv_kernels: [1, 3, 5, 7, 9, 11, 13, 15]
        output_dim: 192
    
    pressure:
      type: "lstm"
      params:
        hidden_dim: 64
        num_layers: 2
        dropout_rate: 0.1
        bidirectional: true
        output_dim: 64
  
  # 融合策略配置
  fusion:
    strategy: "concatenate"
    params: {}
  
  # 融合后的输出维度 (192 + 64 = 256)
  fusion_output_dim: 256
  
  # 全局dropout率
  dropout_rate: 0.1

# 训练配置
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  optimizer: "adam"
  scheduler: "cosine"
  weight_decay: 0.0001
  label_smoothing: 0.1
  gradient_clip_norm: 1.0
  early_stopping_patience: 10

# 实验配置
device: "auto"  # auto, cpu, cuda, mps
seed: 42
output_dir: "./results/shl_multimodal"
save_checkpoints: true
verbose: true